services:
  backend:
    build: ./backend
    container_name: webprice-backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
    container_name: webprice-frontend
    ports:
      - "80:80"
  database:
    image: postgres:15-alpine
    container_name: webprice-database
    ports:
      - "5432:5432"