version: '3.8'

services:
  # Serviço do Backend
  backend:
    build: ./backend
    container_name: webprice-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app

  # Serviço do Frontend
  frontend:
    build: ./frontend
    container_name: webprice-frontend
    restart: unless-stopped
    ports:
      - "80:80" # Mapeia a porta 80 do seu PC para a porta 80 do contêiner Nginx
    depends_on:
      - backend

networks:
  default:
    driver: bridge